# Generated by Django 5.2.5 on 2025-08-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sawari_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
