# Generated by Django 5.2.5 on 2025-08-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
