# Generated by Django 5.2.5 on 2025-08-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_acc', '0003_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('user', 'otp')},
        ),
    ]
