# Generated by Django 5.2.5 on 2025-08-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('bus', 'Bus'), ('truck', 'Truck')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('kyc_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_approved', models.BooleanField(default=False)),
                ('kyc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
