# Generated by Django 5.2.5 on 2025-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
