# Generated by Django 5.2.5 on 2025-09-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
