# Generated by Django 5.2.5 on 2025-10-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
