# Generated by Django 5.2.5 on 2025-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('approved', 'Approved')], default='available', max_length=20),
        ),
    ]
