# Generated by Django 5.2.5 on 2025-10-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('approved', 'approved'), ('completed', 'completed')], default='available', max_length=20),
        ),
    ]
